In [13]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

# El Módulo numpy

Voy a escribir textualmente de la página de numpy, que és numpy.<br>
NumPy is the fundamental package for scientific computing with Python. It contains among other things:<br>

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

In [9]:
import numpy as np

# crea un vector fila
vector_row = np.array([1, 2, 3])
print(vector_row)
# crea un vector columna
vector_column = np.array([[1],
                          [2],
                          [3]])
print(vector_row.shape)####.shape muestra las dimensiones de la matriz
print(vector_column.shape)


[1 2 3]
(3,)
(3, 1)


In [24]:
matrix = np.array([[0, 0],
                   [0, 1],
                   [3, 0]])
#matrix1=np.array([0,0,0,1,3,0],(3,2))
matrix
matrix.shape
matrix.ndim
matzeros=np.zeros((3,3))
arr = np.full((4,5), 2)
arr
arreglodim=np.array([1,2,3,4,5,6]).reshape(2,3)
arreglodim

array([[0, 0],
       [0, 1],
       [3, 0]])

(3, 2)

2

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

array([[1, 2, 3],
       [4, 5, 6]])

# Acceder a elementos de una matriz

In [14]:
matrix[1,1]
matrix[0,0]


1

0

# Operaciones entre matrices

In [31]:
matrix1 = np.array([[1, 4],
                   [2, 5]])
matrix2=np.array([[-1,-4],[-2,-5]])
matrix1+matrix2 ###Suma de matrices
matrix1+2  ###Sumar un valor a cada entrada de la matriz
matrix1*3  ####Multiplicar cada entrada de la matriz 
np.linalg.inv(matrix1)###Inversa de la matriz
matrix1 @ np.linalg.inv(matrix1)  ####Producto de matrices


array([[0, 0],
       [0, 0]])

array([[3, 6],
       [4, 7]])

array([[ 3, 12],
       [ 6, 15]])

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

array([[1., 0.],
       [0., 1.]])

# Creación de arrrglos Multidimensionales

In [40]:
x3d=np.array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],
       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],
       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])
x3d.shape
x3d
type(x3d)
x3d[0,0,0]
x3d[0,0,2]
x3d[0,2,2]
x3d[2,0,0]

(3, 3, 3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

numpy.ndarray

0

2

8

18